### ISSUE TITLE
Pokemon with different types (mega-absol, Deoxys-attack, Giratina-origin etc) have wrong Dex ID

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#16]
![image](https://user-images.githubusercontent.com/3722350/138614067-61038411-b25d-4bae-a060-ebd057729a82.png)

Based on the API we are using, whenever the pokemon has an altered form that is looked up the ID the API assigns it starts at 10000 and works from there. Looking through the object we should be using the `pokemon-species` lookup as it generates the national dex (as well as other dex IDs) and lists all their alternative forms

**Comment by jeremy-jtlo** [comment]
We can probably hide the mega forms from the search results and query all with ID < 10000.

Later on we'll need support for mega forms as part of `PokemonDTO`
