### ISSUE TITLE
Meostic has a larger shiny sprit

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#27]
![image](https://user-images.githubusercontent.com/3722350/140677573-0bc41c92-cc88-49b0-9c60-9f841d9d3b03.png)

For whatever reason, Meostic's shiny sprite is larger. The solution to this could be to enforce a width/height to sprites, I believe most sprites are 96x96

**Comment by gdirk07** [comment]
A forced resize doesn't fully resolve this issue, the problem seems to be the source image. Our Options are

1. Download the sprite -> fix it -> store it locally to upload
2. Ask if the owner of the API can fix it
3. leave it alone


![image](https://user-images.githubusercontent.com/3722350/142749753-0188e6bd-7207-4c35-96ed-6faacf976a28.png)

**Comment by gdirk07** [comment]
Since there's a chance there could be more than one disturbed sprite, it might be worth while to extract all the sprites the API has to offer and compare sizes. Its a lower priority issue since I rather get more features/core components created before hand

**Comment by jeremy-jtlo** [comment]
We could automate this via python, but yeah I agree it's probably lower priority.

I have a nagging suspicion there is a way to enforce a 'fix' in the view itself by getting creative with CSS, but that will take a lot more reading than I have time for at the moment.

**Comment by gdirk07** [comment]
For Now I capped the size to be 96x96 pixels
