### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#3]
A lot of the code execution and displays happens at the top level that could possibly happen in the Children components (API fetching could be handled in a different component).

Highest priority as it will also help with architecting future components

**Comment by jeremy-jtlo** [comment]
This is dependant on #4 , which I'm hoping to address by introducing a pokemon repository as well as a move repo.

**Comment by gdirk07** [comment]
Closing this since it was something made for when I was (re) kicking off this project and the codebase has gone through many refactors, at this point it means nothing and will be revisited under a new issue when it needs to be
