### ISSUE TITLE
Migrate the CSS to in-component

### ISSUE THREAD

**Issue by jeremy-jtlo** [gdirk07/PokemonChecker#36]
Per the discussion offline, it's been decided that we'll sunset the explicit `.css` files and move forward with [React Component styling](https://reactjs.org/docs/dom-elements.html#style).

Files to migrate/deprecate:

- PokemonDisplayStyle.css
- PokemonSearch.css
- App.css
- index.css

Because React allows us to define styles as objects in our components, it gives us the power to leverage explicit TS logic to define how a component renders, rather than learning too hard on media queries or assigning different classes based on state.

**Comment by gdirk07** [comment]
As per a later issue, we are going with Material UI, will close this issue when the changes are made

**Comment by gdirk07** [comment]
Closed with the merge of #39
