### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#4]
We request Pokemon everytime we select a new one, if we already fetched a pokemon, instead of requesting it again, lets access it locally.

**Comment by jeremy-jtlo** [comment]
I'm thinking about adding a couple repositories with the move changes. Doing so will likely mean the service structure has to change (constructing URLs via function params, other goodies).

**Comment by jeremy-jtlo** [comment]
Found some [documentation on MDN](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage) that can give us a hand with this. I'll see if I can glean anything from it and implement a client-side repository for Pokemon and Move data.
