### ISSUE TITLE
Art assets?

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#42]
I'm thinking some parts can use art assets, such as an icon, or how we display typing (could probably rip them from somewhere) instead of text. This is a very broad issue, so we can move it to a discussion

**Comment by jeremy-jtlo** [comment]
I'm also wondering if the API would also give us the "small" sprites in case we want simplified views (what you'd see in the party menu).

Assets for displaying type would contribute to 1.0 (displaying pokemon as cards), but the mini-sprites are probably a much lower priority.

**Comment by gdirk07** [comment]
I'm mostly concerned with how the types are displayed now, they are plain, I was thinking of colour coding each type, but something that matches ingame would be more pleasant and recognizable

**Comment by jeremy-jtlo** [comment]
Wait that's a good point

We can accomplish the exact same thing using a combo of `border-radius`, `color`, and `background-color` rules.

That means we'd want to have a view class for type display, that relies on our existing `ITypeData`. We can use the colour picker in firefox to even get the values from a site with the assets.

In firefox you can hit F12, select an element with a colour rule, and then click on the little circle with the colour value. Doing that will give you the picker tool, which can just sample from the page you're viewing:

![image](https://user-images.githubusercontent.com/3711737/149228825-c431497e-0faa-476c-8ed8-25efdec6dda8.png)

**Comment by gdirk07** [comment]
That's good to know, We can do something like this if we are choose not to go with official assets

**Comment by gdirk07** [comment]
> I'm also wondering if the API would also give us the "small" sprites in case we want simplified views (what you'd see in the party menu).

I understand what you mean, and I see where exist in the api but only gen6-8 in "https://pokeapi.co/api/v2/pokemon/ditto/sprites/versions/generation-viii/icons/front_default" gives you [this](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/132.png) as an example
