### ISSUE TITLE
Evolution Path

### ISSUE THREAD

**Issue by gdirk07** [gdirk07/PokemonChecker#48]
I can't remember if we had it in the writeup or discussion, but concerning evolution paths, how/where do we want to display it? Do we display it in the "QuickView" for this or will these be information for a more detailed view down the line?

On that topic, how do we wanna display Mega Evolutions? Or different Forms? I'm not sure we need to display the data itself in the quick view, but maybe a couple sentence strings

"Fully Evolved? Yes" (if its a final stage)
"Has Mega? No" (if it has a Mega)
"Alternate Forms? No" (If it has multiple forms)

![image](https://user-images.githubusercontent.com/3722350/149235600-069dee4b-abc2-4eed-9150-8e44d8361169.png)
I think there's room under the sprite and above the total stats to fit these.

**Comment by gdirk07** [comment]
Would require extra components and possible lookups if the API can't get these answers directly, but I think its worth it to have this information from a UX point of view. Don't necessary need to link them to those mons here, but if users want to know more they can find it in our "full details" feature I believe we have planned for milestone 2

**Comment by jeremy-jtlo** [comment]
We can go over this in person with some hand drawn diagrams.

Optimally I'd like a "summary" card and a "full details" card, that way we can display pokemon that you want to see without shoveling 100% of the PokemonDTO payload onto the screen at all times.

**Comment by gdirk07** [comment]
I think that's what we discussed last meeting, we want a quick view with important details with more details/fluff on its own feature. I still think we should add the strings somewhere since knowing if a Mon has other forms/Mega is kind of important, even if we don't go into details, it could be even searchable in the far future

**Comment by gdirk07** [comment]
Doing some research on this, its "possible" but requires performing more calls and fetches (to pokemon-species, to get the varieties which contains an entry for a mega if it exists, evolution-chain we need to fetch to get the entire evo line and check if its at the end etc). While I still think this is useful information to have before hand, I'm not sure its viable to fetch a few more objects or the time constraint, as well as how we want to configure the data pipeline.

**Comment by gdirk07** [comment]
Going to close this since nothing is really coming up. It can be revisited under a new issue in the future if we want to propagate some information from "full details" to "quick view"
